theme: jekyll-theme-so-simple
skin: /assets/css/skins/default.css
locale: en-US
title: My Awesome Site
description: It really is the best.
baseurl: ''
url: ''
logo: null
date_format: '%B %-d, %Y'
read_time: null
words_per_minute: null
mathjax:
  enable: null
  combo: null
  tags: null
google_fonts:
  - name: Source Sans Pro
    weights: '400,400i,700,700i'
  - name: Lora
    weights: '400,400i,700,700i'
google_analytics: null
disqus:
  shortname: null
twitter:
  username: null
liquid:
  error_mode: strict
permalink: '/:categories/:title/'
markdown: kramdown
feed:
  path: atom.xml
search_full_content: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      share: true
author:
  name: null
  picture: null
  email: null
  twitter: null
  links:
    - title: null
      url: null
      icon: null
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
